baseURL = "/"
title = "CUE"
publishDir = "_public"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true  # Useful when translating

enableRobotsTXT = true # Render robots.txt
enableGitInfo = true # Will give git-info values to .Lastmod etc.
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
disableAliases = true # We use Netlify server-side redirects instead of generated aliases

# Hugo allows theme composition (and inheritance). Precedence is from left to right.
# theme = ["docsy"]

# Highlighting
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false # Use the new Chroma Go highlighter in Hugo.
# pygmentsOptions = "linenos=table"
pygmentsStyle = "tango" # See https://help.farbox.com/pygments.html

# Image processing
[imaging]
    # See https://github.com/disintegration/imaging
    # CatmullRom is a sharp bicubic filter which should fit the docs site well with its many screenshots.
    # Note - you can also set this per image processing.
    resampleFilter = "CatmullRom"
    # Default JPEG quality setting. Default is 75.
    quality = 75
    anchor = "smart"

# Output configuration
[outputs]
    home = ["HTML", "RSS", "REDIR"]
    section = ["HTML"]

[outputFormats]
    [outputFormats.RSS]
        baseName = "feed"
    [outputFormats.REDIR]
        mediatype = "text/netlify"
        baseName = "_redirects"
        isPlainText = true
        notAlternative = true

[mediaTypes]
    [mediaTypes."text/netlify"]
        delimiter = ""

[social]
    twitter = "cue_lang"

# [services]
#     [services.googleAnalytics]
#         id = "UA-00000000-0" # Comment out to disable GA tracking. Also disables the feature [params.ui.feedback]
