# Languages
[en]
    languageName = "English"
    contentDir = "content/en"
    languageDirection = "ltr"
    title = "CUE"
    description = "Validate and define text-based and dynamic configuration"
    time_format = "January 2, 2006"
    weight = 1

[zh-cn]
    languageName = "简体中文"
    contentDir = "content/zh"
    languageDirection = "ltr"
    title = "CUE"
    description = "验证、定义、使用动态以及文本式的数据"
    time_format = "January 2, 2006"
    weight = 2
