[build]
  functions = "functions"
  publish = "_public"
  command = "bash build.bash"

[build.environment]
HUGO_ENV = "production"
GO_VERSION = "1.18.5"
NODE_VERSION = "18.8.0"
HUGO_VERSION = "0.89.4"

[context.deploy-preview]
command = "bash build.bash -b $DEPLOY_URL"

[[redirects]]
  from = "/cl/*"
  to = "https://review.gerrithub.io/c/cue-lang/cue/+/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/issue/*"
  to = "https://github.com/cue-lang/cue/issues/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/issues/*"
  to = "https://github.com/cue-lang/cue/issues/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/discussion/*"
  to = "https://github.com/cue-lang/cue/discussions/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/discussions/*"
  to = "https://github.com/cue-lang/cue/discussions/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/releases/*"
  to = "https://github.com/cue-lang/cue/releases/:splat"
  status = 302
  force = true
