[build]
  functions = "_functions"
  publish = "_public"
  command = "sh build.sh"

[build.environment]
HUGO_ENV = "production"
GO_VERSION = "1.17.3"
NODE_VERSION = "16.13.0"
HUGO_VERSION = "0.89.4"

[context.deploy-preview]
command = "sh build.sh -b $DEPLOY_URL"

[[redirects]]
  from = "https://cuelang.org/issue/*"
  to = "https://github.com/cue-lang/cue/issues/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://cuelang.org/issues/*"
  to = "https://github.com/cue-lang/cue/issues/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://cuelang.org/discussion/*"
  to = "https://github.com/cue-lang/cue/discussions/:splat"
  status = 302
  force = true
