// Code generated by "stringer -type=opType -linecomment"; DO NOT EDIT.

package fsnotify

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[addOpType-0]
	_ = x[removeOpType-1]
}

const _opType_name = "addremove"

var _opType_index = [...]uint8{0, 3, 9}

func (i opType) String() string {
	if i >= opType(len(_opType_index)-1) {
		return "opType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _opType_name[_opType_index[i]:_opType_index[i+1]]
}
