defaultMarkdownHandler = "goldmark"

[goldmark]
[goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
[goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"
[goldmark.parser.attribute]
    block = true
    title = true
[goldmark.renderer]
    hardWraps = false
    unsafe = true # Renderer requires this for raw HTML to be displayed
    xhtml = false

[highlight]
    style = "trac"

[tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2
