package site
{
	content: {
		docs: {
			draft: {
				cldd: {
					"getting-started-with-github-actions-cue": {
						page: {
							cache: {
								upload: {
									gitignore: "YIk1/rgL7E55N9JrrJJ3By4p+cElB4fb1aXjTfWxuQQ="
									"1":       "kvbfkLDuBE6xPIWem8VrH4ETHT0ANsbLem2FoGWKq70="
									yaml:      "DMg6E09RqI7w9PAmN22AEKY6PLqWTzPL7Czd7AAkvsc="
								}
								multi_step: {
									hash:       "4TCGHP6QONANBLA3H4S3IIHOIKN91QMDCF1JCUA58I6JJV0QUN1G===="
									scriptHash: "A058C35GOOLAMCRDJ5MF47MNE5NML886USOPLHVJF7PPNMM5AB4G===="
									steps: [{
										doc:      "# Registry auth"
										cmd:      "mkdir -p $HOME/.config/cue"
										exitCode: 0
										output:   ""
									}, {
										doc: ""
										cmd: """
												cat <<EOD >$HOME/.config/cue/logins.json
												{"registries":{"registry.cue.works":{"access_token":"${TEST_USER_AUTHN_CUE_USER_NEW}","token_type":"Bearer"}}}
												EOD
												"""
										exitCode: 0
										output:   ""
									}, {
										doc:      "# Local git repo"
										cmd:      "git config --global user.email 'user@cue.example'"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "git config --global user.name user"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "git init -q"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "cue mod init"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "cue mod tidy"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "cue vet -c"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "mkdir -p .github/workflows/"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "cue export --outfile .github/workflows/workflow.yml"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "mv .github/workflows/workflow.yml .workflow.yml"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "diff .github/workflows/workflow.yml .workflow.yml"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "git add -v cue.mod .github/workflows/ workflow.cue"
										exitCode: 0
										output: """
												add '.github/workflows/workflow.yml'
												add 'cue.mod/module.cue'
												add 'workflow.cue'

												"""
									}, {
										doc:      ""
										cmd:      "git commit -q -m 'Add GitHub Actions workflow validated by CUE'"
										exitCode: 0
										output:   ""
									}, {
										doc:      "# This checks that the preceding git commands didn't miss any user-visible files generated by the rest of the page."
										cmd:      "test -z \"$(git status --porcelain)\" || (git status; git --no-pager diff; false)"
										exitCode: 0
										output:   ""
									}]
								}
							}
						}
					}
				}
			}
		}
	}
}
