package site
{
	content: {
		docs: {
			draft: {
				cldd: {
					"getting-started-with-gitlab-cicd-cue": {
						page: {
							cache: {
								upload: {
									gitignore: "QVoli2wppJ9j2gi3EXcpFdOejVH0lt5inssg5sK4lCY="
									"1":       "HptPK+//ElS6SJt6i09J5YLYFUMziTmPmfewdnExZeY="
									yaml:      "WEDCLBFB4WigMMB+SvHJubUzHEtg67uFlDuq0apDuQQ="
								}
								multi_step: {
									hash:       "V2EK76TL6CH0K02K2DH50ESOOJT6A3N1OCDJQHR14N0UM6C62JGG===="
									scriptHash: "PU039V17BJ479RRGTKGIJD2LNDC3TRV1G42MPKM6RLVMJ2RDBMD0===="
									steps: [{
										doc:      "# Registry auth"
										cmd:      "mkdir -p $HOME/.config/cue"
										exitCode: 0
										output:   ""
									}, {
										doc: ""
										cmd: """
												cat <<EOD >$HOME/.config/cue/logins.json
												{"registries":{"registry.cue.works":{"access_token":"${TEST_USER_AUTHN_CUE_USER_NEW}","token_type":"Bearer"}}}
												EOD
												"""
										exitCode: 0
										output:   ""
									}, {
										doc:      "# Local git repo"
										cmd:      "git config --global user.email 'user@cue.example'"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "git config --global user.name user"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "git init -q"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "cue mod init"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "cue mod tidy"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "cue vet -c"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "cue export --outfile .gitlab-ci.yml"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "mv .gitlab-ci.yml .pipeline.yml"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "diff .gitlab-ci.yml .pipeline.yml"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "git add -v cue.mod .gitlab-ci.yml pipeline.cue"
										exitCode: 0
										output: """
												add '.gitlab-ci.yml'
												add 'cue.mod/module.cue'
												add 'pipeline.cue'

												"""
									}, {
										doc:      ""
										cmd:      "git commit -q -m 'Add GitLab CI/CD pipeline validated by CUE'"
										exitCode: 0
										output:   ""
									}, {
										doc:      "# This checks that the preceding git commands didn't miss any user-visible files generated by the rest of the page."
										cmd:      "test -z \"$(git status --porcelain)\" || (git status; git --no-pager diff; false)"
										exitCode: 0
										output:   ""
									}]
								}
							}
						}
					}
				}
			}
		}
	}
}
