package site
{
	content: {
		docs: {
			draft: {
				cldd: {
					"getting-started-with-gitlab-cicd-cue": {
						page: {
							cache: {
								upload: {
									gitignore: "QVoli2wppJ9j2gi3EXcpFdOejVH0lt5inssg5sK4lCY="
									"1":       "HptPK+//ElS6SJt6i09J5YLYFUMziTmPmfewdnExZeY="
									yaml:      "WEDCLBFB4WigMMB+SvHJubUzHEtg67uFlDuq0apDuQQ="
								}
								multi_step: {
									hash:       "B799R297Q6AJCQRTN43I2GT1DB02DLIN5BJMHTPFSEEGQQS7664G===="
									scriptHash: "EOKKQVSHVRCDFBDNGV6TGCJ66DR58B3KEJ3HKL61SRKB3EAQA6L0===="
									steps: [{
										doc:      "# Registry auth"
										cmd:      "mkdir -p $HOME/.config/cue"
										exitCode: 0
										output:   ""
									}, {
										doc: ""
										cmd: """
												cat <<EOD >$HOME/.config/cue/logins.json
												{"registries":{"registry.cue.works":{"access_token":"${TEST_USER_AUTHN_CUE_USER_NEW}","token_type":"Bearer"}}}
												EOD
												"""
										exitCode: 0
										output:   ""
									}, {
										doc:      "# Local git repo"
										cmd:      "git config --global user.email 'user@cue.example'"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "git config --global user.name user"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "git init -q"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "cue mod init"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "cue mod tidy"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "cue vet -c"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "cue export --outfile .gitlab-ci.yml"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "mv .gitlab-ci.yml .pipeline.yml"
										exitCode: 0
										output:   ""
									}, {
										doc:      ""
										cmd:      "diff --side .gitlab-ci.yml .pipeline.yml"
										exitCode: 0
										output: """
												default:\t\t\t\t\t\t\tdefault:
												  image: ruby:3.2\t\t\t\t\t\t  image: ruby:3.2
												workflow:\t\t\t\t\t\t\tworkflow:
												  rules:\t\t\t\t\t\t\t  rules:
												    - if: $CI_COMMIT_BRANCH\t\t\t\t\t    - if: $CI_COMMIT_BRANCH
												deploy-pages:\t\t\t\t\t\t\tdeploy-pages:
												  rules:\t\t\t\t\t\t\t  rules:
												    - if: $CI_COMMIT_BRANCH == "main"\t\t\t\t    - if: $CI_COMMIT_BRANCH == "main"
												  script:\t\t\t\t\t\t\t  script:
												    - gem install bundler\t\t\t\t\t    - gem install bundler
												    - bundle install\t\t\t\t\t\t    - bundle install
												    - bundle exec jekyll build -d public\t\t\t    - bundle exec jekyll build -d public
												  stage: deploy\t\t\t\t\t\t\t  stage: deploy
												  environment: production\t\t\t\t\t  environment: production
												  pages: true\t\t\t\t\t\t\t  pages: true
												test:\t\t\t\t\t\t\t\ttest:
												  rules:\t\t\t\t\t\t\t  rules:
												    - if: $CI_COMMIT_BRANCH != "main"\t\t\t\t    - if: $CI_COMMIT_BRANCH != "main"
												  script:\t\t\t\t\t\t\t  script:
												    - gem install bundler\t\t\t\t\t    - gem install bundler
												    - bundle install\t\t\t\t\t\t    - bundle install
												    - bundle exec jekyll build -d test\t\t\t\t    - bundle exec jekyll build -d test
												  stage: test\t\t\t\t\t\t\t  stage: test
												  artifacts:\t\t\t\t\t\t\t  artifacts:
												    paths:\t\t\t\t\t\t\t    paths:
												      - test\t\t\t\t\t\t\t      - test

												"""
									}, {
										doc:      ""
										cmd:      "git add -v cue.mod .gitlab-ci.yml pipeline.cue"
										exitCode: 0
										output: """
												add '.gitlab-ci.yml'
												add 'cue.mod/module.cue'
												add 'pipeline.cue'

												"""
									}, {
										doc:      ""
										cmd:      "git commit -q -m 'Add GitLab CI/CD pipeline validated by CUE'"
										exitCode: 0
										output:   ""
									}, {
										doc:      "# This checks that the preceding git commands didn't miss any user-visible files generated by the rest of the page."
										cmd:      "test -z \"$(git status --porcelain)\" || (git status; git --no-pager diff; false)"
										exitCode: 0
										output:   ""
									}]
								}
							}
						}
					}
				}
			}
		}
	}
}
