"on":
  push:
    branches:
      - master
  repository_dispatch: {}
  pull_request:
    branches:
      - '**'
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.9.0
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
      - name: Ensure latest CUE
        run: |
          GOPROXY=direct go get -d cuelang.org/go@latest
          go mod tidy
          cd play
          GOPROXY=direct go get -d cuelang.org/go@latest
          go mod tidy
      - name: Re-vendor play
        run: ./_scripts/revendorToolsInternal.bash
        working-directory: ./play
      - name: Regenerate
        run: go generate ./...
      - name: Regenerate play
        run: go generate ./...
        working-directory: ./play
      - name: Test
        run: go test ./...
      - name: Test play dist
        run: NETLIFY=true NETLIFY_BUILD_BASE=$(mktemp -d) ./build.bash
        working-directory: ./play
      - name: Check module is tidy
        run: go mod tidy
      - name: Check play module is tidy
        run: go mod tidy
        working-directory: ./play
      - name: Verify commit is clean
        run: test -z "$(git status --porcelain)" || (git status; git diff; false)
      - name: Test play dist at tip
        run: NETLIFY=true NETLIFY_BUILD_BASE=$(mktemp -d) BRANCH=tip ./build.bash
        working-directory: ./play
