site_name: "CUE"
site_url: "https://cuelang.org/mkdocs/docs/"
strict: false # FIXME: enable strict mode

# docs_dir, site_dir, and watch are relative to this config file.
docs_dir: "source/"
site_dir: "../hugo/static/mkdocs/"
watch:
  - "overrides/"

use_directory_urls: true

extra_css:
  - assets/stylesheets/docs.css

theme:
  name: material
  custom_dir: overrides/
  # logo: assets/images/logo.svg
  # favicon: assets/images/favicon.svg
  features:
  #   - content.code.copy # copy buttons on code blocks
  #   - navigation.tabs # horizontal nav bar in page header
  #   - navigation.tabs.sticky # horizontal nav bar is always visible
  #   - navigation.sections
  #   - announce.dismiss # notification bar can be dismissed
    - header.autohide # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#automatic-hiding
    - navigation.tabs # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.indexes # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
      # Pruning feels like a good idea, given its description. With navigation.indexes we won't have expandable
      # sections, so why wouldn't we enable it? FIXME: check UI when a section doesn't have an index - might that occur?
    - # navigation.prune # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-pruning

hooks:
  - hooks/faux_nav.py

# Page titles:
# IF a page title is set here in the nav struct (e.g. "foo: some/page/index.md") then the title is set not only for the
# nav, but also as the on-page title - overriding the page's "title" front matter field.
# UNLESS the page's Markdown contains an H1 - in which case the nav displays the title set here, and the page displays
# the H1 at the top - omitting either of the nav's setting or the source's "title" front matter.
# Neither of these links fully describes this observed behaviour, but are relevant:
# - https://squidfunk.github.io/mkdocs-material/reference/#setting-the-page-title
# - https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data
nav:
  - docs/index.md
  - Introduction:
    - docs/introduction/index.md
    - docs/introduction/installation/index.md
  - Tour:
    - docs/tour/index.md
    - docs/tour/basics/index.md
    - docs/tour/types/index.md
    - docs/tour/references/index.md
    - docs/tour/expressions/index.md
    - docs/tour/packages/index.md
  - Integrations:
    - docs/integration/index.md
    - docs/integration/openapi/index.md
    - docs/integration/json/index.md
    - docs/integration/yaml/index.md
    - docs/integration/protobuf/index.md
  - Tutorials:
    - docs/tutorial/index.md
    - docs/tutorial/new-to-cue/index.md
  - How-to Guides:
    - docs/howto/index.md
    - docs/howto/popular-guides/index.md
    - Commented CUE Guides: docs/missing/FIXME.md
  - Concept Guides:
    - docs/concept/index.md
    - Popular guides: docs/concept/popular-guides/index.md
    - The Logic of CUE: docs/missing/FIXME.md
    - Modules: docs/concept/modules/index.md
    - Frequently Asked Questions: docs/concept/faq/index.md
  - References:
    - docs/reference/index.md
    - docs/reference/spec/index.md
    - docs/reference/glossary/index.md
    - docs/reference/command/index.md
    - docs/reference/code-of-conduct/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cue-lang/cue
      name: GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/cue_lang
      name: Twitter
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/cuelang.org
      name: Bluesky
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@cuelang/videos
      name: YouTube
    - icon: fontawesome/brands/slack
      link: https://cuelang.org/s/slack
      name: Slack
    - icon: fontawesome/brands/discord
      link: https://cuelang.org/s/discord
      name: Discord

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      # Required by MkDocs Material
      alternate_style: true
      # Better URL fragment links for content tabs
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: "#"

validation:
  nav:
    absolute_links: ignore
    not_found: warn
    omitted_files: info
  links:
    absolute_links: ignore
    anchors: warn
    not_found: warn
    unrecognized_links: warn
